#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

NAME=clienthistory
PROG=/usr/sbin/clienthistory

start_service() {
	mkdir -p /var/lib/clienthistory

	procd_open_instance "$NAME"
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
